# Service(systemctl service name)
service:
  - name:  docker
  - name:  cloudit-5.0
  - name:  mariadb

# Web
web:
  - name: FEMS-harbor
    url: https://registry.fems.cf
  - name: naver
    url: https://naver.com/

# Network(HOST) /etc/hosts
network:
  - kind: host
    name: network03
    ip: 8.8.8.8
  - kind: port
    name: port01
    protocol: ssh
    ip: 101.79.1.154
    port: 22